
package client;

/**
 *
 * @author ematsak
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        canvas1 = new Class1();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        canvas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hiireClick(evt);
            }
        });
        canvas1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                klahvid(evt);
            }
        });

        jLabel1.setText("Punkte:");

        jLabel2.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    private void hiireClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hiireClick
        // TODO add your handling code here:
        System.out.println("vajutasid");
        System.out.println(evt.getX());
        System.out.println(evt.getY());
        x=evt.getX();
        y=evt.getY();
        canvas1.repaint();
    }//GEN-LAST:event_hiireClick

    private void klahvid(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_klahvid
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_DOWN){
            System.out.println("vajutasid alla");
            y1=y1+10;
        }
        if(evt.getKeyCode()==evt.VK_UP){
            System.out.println("vajutasid ylesse");
            y1=y1-10;
        }
        
        if(evt.getKeyCode()==evt.VK_RIGHT){
            System.out.println("vajutasid paramele");
            x1=x1+10;
        }
        if(evt.getKeyCode()==evt.VK_LEFT){
            System.out.println("vajutasid vasakule");
            x1=x1-10;
        }
        
        int y2_1=200;
        int y2_2=200+100-70;
        int x2_1=10;
        int x2_2=110-70;
        
        if((x1>=x2_1) & (x1<=x2_2)& (y1>=y2_1)&(y1<=y2_2)){
            System.out.println("liblikas on kasti sees, liblika asukoht on "+ x1+ " ja " +y1);
        }
        else{
            System.out.println("liblikas on kastist väljas või osaliselt väljas, liblika asukoht on "+ x1+ " ja " +y1);
        }
        
        
        if((x1>=Class1.x4) & (x1<=Class1.x4+70)& (y1>=Class1.y4)&(y1<=Class1.y4+70)){
            System.out.println("liblikas on lillekese peal, liblika asukoht on "+ Class1.x4+ " ja " +Class1.y4);
            int punkte=Integer.parseInt(jLabel2.getText());
            punkte=punkte+1;
            //punkte++
            jLabel2.setText(""+punkte);
            
            Class1.x4=-70;
            Class1.y4=-70;
        }
        
        
        canvas1.repaint();
    }//GEN-LAST:event_klahvid

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(NewJFrame.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(NewJFrame.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(NewJFrame.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(NewJFrame.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new NewJFrame().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    static int x=0;
    static int y=0;
    static int x1=200;
    static int y1=200;
}
